# Generated by Django 4.2.13 on 2024-07-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
