# Generated by Django 4.2.13 on 2024-07-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_quiz_user_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
