# Generated by Django 4.2.13 on 2024-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_quiz_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
