# Generated by Django 4.2.13 on 2024-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_userprofile_is_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
