# Generated by Django 4.2.13 on 2024-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_note_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject_id',
            field=models.CharField(max_length=10),
        ),
    ]
