# Generated by Django 4.2.13 on 2024-07-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_note_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='unnamed note', max_length=256),
        ),
    ]
