# Generated by Django 4.2.13 on 2024-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_progress',
            field=models.FloatField(default=0),
        ),
    ]
