# Generated by Django 4.2.13 on 2024-07-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_note_note_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
