# Generated by Django 4.2.13 on 2024-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_note_user_note_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=25000),
        ),
    ]
