# Generated by Django 4.2.13 on 2024-07-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_note_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AddField(
            model_name='subject',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
