# Generated by Django 4.2.13 on 2024-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_subject_user_subject_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='group_practical_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='practical_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='research_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=23000),
        ),
    ]
