# Generated by Django 4.2.13 on 2024-07-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_note_group_practical_required_note_is_practical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_practical',
        ),
    ]
