# Generated by Django 4.2.13 on 2024-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_note_is_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='important_questions',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
