# Generated by Django 4.2.13 on 2024-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_note_important_questions_alter_note_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('research', models.CharField(max_length=4000)),
                ('submitted_research', models.CharField(default='', max_length=2000)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
