# Generated by Django 4.2.13 on 2024-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='note_id',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
