# Generated by Django 4.2.13 on 2024-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_research_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('project', models.CharField(max_length=4000)),
                ('submitted_research', models.CharField(default='', max_length=2000)),
                ('score', models.FloatField(default=0)),
                ('note_id', models.CharField(default='0', max_length=256)),
            ],
        ),
    ]
