# Generated by Django 4.2.13 on 2024-07-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='submitted_research',
            new_name='submitted_project',
        ),
    ]
