# Generated by Django 4.2.13 on 2024-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_rename_submitted_research_project_submitted_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
