# Generated by Django 4.2.13 on 2024-07-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_project_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default='', upload_to='web/Project/'),
        ),
        migrations.AddField(
            model_name='research',
            name='file',
            field=models.FileField(default='', upload_to='web/Research/'),
        ),
    ]
