# Generated by Django 4.2.13 on 2024-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_project_submitted_project_project_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='needs_improvement',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
