# Generated by Django 4.2.13 on 2024-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_userprofile_needs_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
    ]
