# Generated by Django 4.2.13 on 2024-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_note_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_brief',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
