# Generated by Django 4.2.13 on 2024-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_note_note_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_brief',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
